remote_theme: thefirethirteen/slate

plugins:
- jekyll-remote-theme

contributors:
  text: manuals contributors
  url: https://thefirethirteen.github.io/manuals/manuals/manuals-meta/contributors

license:
  default:
    fancy_name: CC BY-SA 4.0
    url: https://creativecommons.org/licenses/by-sa/4.0/
