remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme

contributors:
  text: manuals contributors
  url: https://github.com/thefirethirteen/manuals/blob/main/contributors.md

license:
  default:
    fancy_name: CC BY-SA 4.0
    url: https://creativecommons.org/licenses/by-sa/4.0/
